site_name: ArchBtw
site_author: mimi
site_url: https://l0vemimi.github.io/ArchBtw/
nav:
  - Home: 'index.md'
  - ManPages:
    - Installation:
      - Install: 'manpages/install.md'
    - System Admin:
      - System: 'manpages/system/system.md'
    - Pacman:
      - MakePkg: 'manpages/pacman/makepkg.md'
  - PackageList: 'pkglist.md'
extra_css:
  - stylesheets/extra.css
dev_addr: 127.0.0.1:8001
theme:
  name: material
  palette:
    primary: white
#    primary: custom
    accent: light blue 
    scheme: default  # light mode
#    scheme: slate    # dark mode
  favicon: arch.png
  logo: arch.png
  icon: 
    note: octicons/tag-16
    abstract: octicons/checklist-16
    info: octicons/info-16
    tip: octicons/squirrel-16
    success: octicons/check-16
    question: octicons/question-16
    warning: octicons/alert-16
    failure: octicons/x-circle-16
    danger: octicons/zap-16
    bug: octicons/bug-16
    example: octicons/beaker-16
    quote: octicons/quote-16
    edit: material/pencil
    view: material/eye
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.expand
    - navigation.path
    - toc.follow
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - header.autohide
    - navigation.footer
    - content.action.edit
    - content.code.copy
    - content.code.select
plugins:
  - search:
      enabled: true
      separator: '[\s\-,:!=\[\]()"/]+|(?!\b)(?=[A-Z][a-z])|\.(?!\d)|&[lg]t;'
      lang: en
  - tags:
      enabled: true
      tags: true
extra:
  version:
    provider: mimi
    default: stable
  status: 
    new: recently added
    depreceated: old
  generator: false
markdown_extensions: 
  - attr_list
  - admonition
  - md_in_html
  - smarty
  - markdown.extensions.wikilinks
  - pymdownx.caret # for superscript in md: H~2~O or A^T^A
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.keys
  - pymdownx.blocks.caption
  - pymdownx.superfences
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx-inline
      line_spans: __span
      use_pygments: true
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true